# Generated by Django 4.2.6 on 2023-11-25 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswersSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(max_length=128)),
                ('incorrect_answer1', models.CharField(max_length=128)),
                ('incorrect_answer2', models.CharField(max_length=128)),
                ('incorrect_answer3', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TriviaQuestion',
            fields=[
                ('user_answer', models.CharField(blank=True, max_length=128, null=True)),
                ('category', models.CharField(max_length=200)),
                ('difficulty', models.CharField(max_length=10)),
                ('question', models.TextField(max_length=500)),
                ('type', models.CharField(max_length=15)),
                ('is_answered', models.BooleanField(default=False)),
                ('answer_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='game.answersset')),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Game', max_length=128)),
                ('game_questions', models.ManyToManyField(blank=True, to='game.triviaquestion')),
            ],
        ),
    ]
